# NumPy

In [1]:
# Author: Anuj Gaikwad
# Date: 24/05/2024

# Numpy is th core library for the scientific and numerical computing
# in python
# it provides high performance multidimentional array object and tools for 
# woking with arrays

# Numpy's main object is the multidimentional array
# it is a table of elements (usually numbers), all the same type, indexed by a tuple
# of positive integers
# In Numpy, dimentions are called axes

In [3]:
import numpy as np

In [6]:
a  = np.array([1,2,3])
print(a)
a

[1 2 3]


array([1, 2, 3])

In [7]:
a[1]

2

In [8]:
import time 
import sys

In [68]:
# comparing python list with numpy array
b = range(1000)
print(sys.getsizeof(5) * len(b))

28000


In [13]:
c = np.arange(1000)
print(c.size * c.itemsize)

4000


In [14]:
size = 100000

In [15]:
L1 = range(size)
L2 = range(size)
A1 = np.arange(size)
A2 = np.arange(size)

In [22]:
start = time.time()
result = [(x + y) for x,y in zip(L1,L2)]
result = [(x + y) for x,y in zip(L1,L2)]
print("python list took :",(time.time()-start)*1000)

python list took : 56.67877197265625


In [23]:
start = time.time()
result = A1 + A2
print("numpy list took :",(time.time()-start)*1000)

numpy list took : 5.003929138183594


In [26]:
a = np.array([[1,2],[3,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 2],
       [3, 4],
       [5, 6]])

In [27]:
a.ndim

2

In [28]:
a.itemsize

4

In [29]:
a.shape

(4, 2)

In [30]:
a = np.array([[1,2],[3,2],[3,4],[5,6]], dtype = np.float64)
a

array([[1., 2.],
       [3., 2.],
       [3., 4.],
       [5., 6.]])

In [31]:
a.itemsize

8

In [32]:
a.shape

(4, 2)

In [36]:
a = np.array([[1,2],[3,2],[3,4],[5,6]], dtype = np.complex128(1))
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [38]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [39]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [40]:
l = range(5)
l

range(0, 5)

In [41]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [44]:
print('concatenation example')
print(np.char.add(['hello ','hi '],['abc','xyz']))

concatenation example
['hello abc' 'hi xyz']


In [50]:
print(np.char.multiply("Hello", 3))

HelloHelloHello


In [54]:
print(np.char.center("Hello", 20, fillchar = '-'))

-------Hello--------


In [56]:
print(np.char.capitalize("hello world"))

Hello world


In [58]:
print(np.char.title("hello world, how you doing"))

Hello World, How You Doing


In [59]:
print(np.char.lower(["HELLO","WORLD"]))
print(np.char.lower("HELLO"))

['hello' 'world']
hello


In [61]:
print(np.char.upper(["python","data"]))
print(np.char.upper("python is easy"))

['PYTHON' 'DATA']
PYTHON IS EASY


In [62]:
print(np.char.split("are you coming to the party?"))

['are', 'you', 'coming', 'to', 'the', 'party?']


In [64]:
print(np.char.splitlines("hello \n are you coming to the party?"))

['hello ', ' are you coming to the party?']


In [65]:
print(np.char.strip(['nina','admin','anita'],'a'))

['nin' 'dmin' 'nit']


In [66]:
print(np.char.join([':','-'],['dmy','ymd']))

['d:m:y' 'y-m-d']


In [67]:
print(np.char.replace("He is a good Dancer",'is','was'))

He was a good Dancer
